### ISSUE TITLE
FloatToByte compiler error

### ISSUE THREAD

**Issue by uutzinger** [paulvha/airquality#1]
Setup:
Arduino IDE 1.8.12
ESP8266 2.7.1
ESP32 1.0.4
airquality example: example10_sps30_aqi.ino  version 1.0.3 / March 2020
Board selected , Sparkfun thing, WEMOS D1 , ...

Compiler error: 
FloattoByte declaration throws error. 
... aqi.cpp:353:17: error: expected ';' before 'conv'
     FloatToBYTE conv;

Attempts to solve issue:
I can not identify where in aqi.h or aqi.cpp the error is as both files look ok to me. 
Documentation states that example 10 has dependencies and to look for them in code. I can not find dependencies listed.
There is call of EEPROM.begin(AQISIZE) which in my esp8266 setup is of return type void while in example program return type boolean is expected. I dont think this is related to declaration error described here unless a new EEPROM library was developed which also affects FloatToByte declaration.

**Comment by paulvha** [comment]
It compiles now. The issue was a definition of the union in aqi.h. New compilers are more strict to syntax and now determined that the definition (accepted in the previous versions of the compiler) was incorrect. Fixed that and uploaded the new aqi.h version.

**Comment by paulvha** [comment]
closing old issues
